import React from 'react';
import {
  StepBackwardOutlined,
  StepForwardOutlined,
  FastBackwardOutlined,
  FastForwardOutlined,
  ShrinkOutlined,
  ArrowsAltOutlined,
  DownOutlined,
  UpOutlined,
  LeftOutlined,
  RightOutlined,
  CaretUpOutlined,
  CaretDownOutlined,
  CaretLeftOutlined,
  CaretRightOutlined,
  UpCircleOutlined,
  DownCircleOutlined,
  LeftCircleOutlined,
  RightCircleOutlined,
  DoubleRightOutlined,
  DoubleLeftOutlined,
  VerticalLeftOutlined,
  VerticalRightOutlined,
  VerticalAlignTopOutlined,
  VerticalAlignMiddleOutlined,
  VerticalAlignBottomOutlined,
  ForwardOutlined,
  BackwardOutlined,
  RollbackOutlined,
  EnterOutlined,
  RetweetOutlined,
  SwapOutlined,
  SwapLeftOutlined,
  SwapRightOutlined,
  ArrowUpOutlined,
  ArrowDownOutlined,
  ArrowLeftOutlined,
  ArrowRightOutlined,
  PlayCircleOutlined,
  UpSquareOutlined,
  DownSquareOutlined,
  LeftSquareOutlined,
  RightSquareOutlined,
  LoginOutlined,
  LogoutOutlined,
  MenuFoldOutlined,
  MenuUnfoldOutlined,
  BorderBottomOutlined,
  BorderHorizontalOutlined,
  PicCenterOutlined,
  PicLeftOutlined,
  PicRightOutlined,
  FullscreenOutlined,
  FullscreenExitOutlined,
  QuestionOutlined,
  QuestionCircleOutlined,
  PlusOutlined,
  PlusCircleOutlined,
  PauseOutlined,
  PauseCircleOutlined,
  MinusOutlined,
  MinusCircleOutlined,
  PlusSquareOutlined,
  MinusSquareOutlined,
  InfoOutlined,
  InfoCircleOutlined,
  ExclamationOutlined,
  ExclamationCircleOutlined,
  CloseOutlined,
  CloseCircleOutlined,
  CloseSquareOutlined,
  CheckOutlined,
  CheckCircleOutlined,
  CheckSquareOutlined,
  ClockCircleOutlined,
  WarningOutlined,
  IssuesCloseOutlined,
  StopOutlined,
  EditOutlined,
  FormOutlined,
  CopyOutlined,
  ScissorOutlined,
  DeleteOutlined,
  SnippetsOutlined,
  DiffOutlined,
  HighlightOutlined,
  AlignCenterOutlined,
  AlignLeftOutlined,
  AlignRightOutlined,
  BgColorsOutlined,
  BoldOutlined,
  ItalicOutlined,
  UnderlineOutlined,
  StrikethroughOutlined,
  RedoOutlined,
  UndoOutlined,
  ZoomInOutlined,
  ZoomOutOutlined,
  FontColorsOutlined,
  FontSizeOutlined,
  LineHeightOutlined,
  DashOutlined,
  SmallDashOutlined,
  SortAscendingOutlined,
  SortDescendingOutlined,
  DragOutlined,
  OrderedListOutlined,
  UnorderedListOutlined,
  RadiusSettingOutlined,
  ColumnWidthOutlined,
  ColumnHeightOutlined,
  AreaChartOutlined,
  PieChartOutlined,
  BarChartOutlined,
  DotChartOutlined,
  LineChartOutlined,
  RadarChartOutlined,
  HeatMapOutlined,
  FallOutlined,
  RiseOutlined,
  StockOutlined,
  BoxPlotOutlined,
  FundOutlined,
  SlidersOutlined,
  AndroidOutlined,
  AppleOutlined,
  WindowsOutlined,
  IeOutlined,
  ChromeOutlined,
  GithubOutlined,
  AliwangwangOutlined,
  DingdingOutlined,
  WeiboSquareOutlined,
  WeiboCircleOutlined,
  TaobaoCircleOutlined,
  Html5Outlined,
  WeiboOutlined,
  TwitterOutlined,
  WechatOutlined,
  YoutubeOutlined,
  AlipayCircleOutlined,
  TaobaoOutlined,
  SkypeOutlined,
  QqOutlined,
  MediumWorkmarkOutlined,
  GitlabOutlined,
  MediumOutlined,
  LinkedinOutlined,
  GooglePlusOutlined,
  DropboxOutlined,
  FacebookOutlined,
  CodepenOutlined,
  CodeSandboxOutlined,
  AmazonOutlined,
  GoogleOutlined,
  CodepenCircleOutlined,
  AlipayOutlined,
  AntDesignOutlined,
  AntCloudOutlined,
  AliyunOutlined,
  ZhihuOutlined,
  SlackOutlined,
  SlackSquareOutlined,
  BehanceOutlined,
  BehanceSquareOutlined,
  DribbbleOutlined,
  DribbbleSquareOutlined,
  InstagramOutlined,
  YuqueOutlined,
  AlibabaOutlined,
  YahooOutlined,
  RedditOutlined,
  SketchOutlined,
  AccountBookOutlined,
  AimOutlined,
  AlertOutlined,
  ApartmentOutlined,
  ApiOutlined,
  AppstoreAddOutlined,
  AppstoreOutlined,
  AudioOutlined,
  AudioMutedOutlined,
  AuditOutlined,
  BankOutlined,
  BarcodeOutlined,
  BarsOutlined,
  BellOutlined,
  BlockOutlined,
  BookOutlined,
  BorderOutlined,
  BorderlessTableOutlined,
  BranchesOutlined,
  BugOutlined,
  BuildOutlined,
  BulbOutlined,
  CalculatorOutlined,
  CalendarOutlined,
  CameraOutlined,
  CarOutlined,
  CarryOutOutlined,
  CiCircleOutlined,
  CiOutlined,
  ClearOutlined,
  CloudDownloadOutlined,
  CloudOutlined,
  CloudServerOutlined,
  CloudSyncOutlined,
  CloudUploadOutlined,
  ClusterOutlined,
  CodeOutlined,
  CoffeeOutlined,
  CommentOutlined,
  CompassOutlined,
  CompressOutlined,
  ConsoleSqlOutlined,
  ContactsOutlined,
  ContainerOutlined,
  ControlOutlined,
  CopyrightOutlined,
  CreditCardOutlined,
  CrownOutlined,
  CustomerServiceOutlined,
  DashboardOutlined,
  DatabaseOutlined,
  DeleteColumnOutlined,
  DeleteRowOutlined,
  DeliveredProcedureOutlined,
  DeploymentUnitOutlined,
  DesktopOutlined,
  DingtalkOutlined,
  DisconnectOutlined,
  DislikeOutlined,
  DollarCircleOutlined,
  DollarOutlined,
  DownloadOutlined,
  EllipsisOutlined,
  EnvironmentOutlined,
  EuroCircleOutlined,
  EuroOutlined,
  ExceptionOutlined,
  ExpandAltOutlined,
  ExpandOutlined,
  ExperimentOutlined,
  ExportOutlined,
  EyeOutlined,
  EyeInvisibleOutlined,
  FieldBinaryOutlined,
  FieldNumberOutlined,
  FieldStringOutlined,
  FieldTimeOutlined,
  FileAddOutlined,
  FileDoneOutlined,
  FileExcelOutlined,
  FileExclamationOutlined,
  FileOutlined,
  FileGifOutlined,
  FileImageOutlined,
  FileJpgOutlined,
  FileMarkdownOutlined,
  FilePdfOutlined,
  FilePptOutlined,
  FileProtectOutlined,
  FileSearchOutlined,
  FileSyncOutlined,
  FileTextOutlined,
  FileUnknownOutlined,
  FileWordOutlined,
  FileZipOutlined,
  FilterOutlined,
  FireOutlined,
  FlagOutlined,
  FolderAddOutlined,
  FolderOutlined,
  FolderOpenOutlined,
  FolderViewOutlined,
  ForkOutlined,
  FormatPainterOutlined,
  FrownOutlined,
  FunctionOutlined,
  FundProjectionScreenOutlined,
  FundViewOutlined,
  FunnelPlotOutlined,
  GatewayOutlined,
  GifOutlined,
  GiftOutlined,
  GlobalOutlined,
  GoldOutlined,
  GroupOutlined,
  HddOutlined,
  HeartOutlined,
  HistoryOutlined,
  HomeOutlined,
  HourglassOutlined,
  IdcardOutlined,
  ImportOutlined,
  InboxOutlined,
  InsertRowAboveOutlined,
  InsertRowBelowOutlined,
  InsertRowLeftOutlined,
  InsertRowRightOutlined,
  InsuranceOutlined,
  InteractionOutlined,
  KeyOutlined,
  LaptopOutlined,
  LayoutOutlined,
  LikeOutlined,
  LineOutlined,
  LinkOutlined,
  Loading3QuartersOutlined,
  LoadingOutlined,
  LockOutlined,
  MacCommandOutlined,
  MailOutlined,
  ManOutlined,
  MedicineBoxOutlined,
  MehOutlined,
  MenuOutlined,
  MergeCellsOutlined,
  MessageOutlined,
  MobileOutlined,
  MoneyCollectOutlined,
  MonitorOutlined,
  MoreOutlined,
  NodeCollapseOutlined,
  NodeExpandOutlined,
  NodeIndexOutlined,
  NotificationOutlined,
  NumberOutlined,
  OneToOneOutlined,
  PaperClipOutlined,
  PartitionOutlined,
  PayCircleOutlined,
  PercentageOutlined,
  PhoneOutlined,
  PictureOutlined,
  PlaySquareOutlined,
  PoundCircleOutlined,
  PoundOutlined,
  PoweroffOutlined,
  PrinterOutlined,
  ProfileOutlined,
  ProjectOutlined,
  PropertySafetyOutlined,
  PullRequestOutlined,
  PushpinOutlined,
  QrcodeOutlined,
  ReadOutlined,
  ReconciliationOutlined,
  RedEnvelopeOutlined,
  ReloadOutlined,
  RestOutlined,
  RobotOutlined,
  RocketOutlined,
  RotateLeftOutlined,
  RotateRightOutlined,
  SafetyCertificateOutlined,
  SafetyOutlined,
  SaveOutlined,
  ScanOutlined,
  ScheduleOutlined,
  SearchOutlined,
  SecurityScanOutlined,
  SelectOutlined,
  SendOutlined,
  SettingOutlined,
  ShakeOutlined,
  ShareAltOutlined,
  ShopOutlined,
  ShoppingCartOutlined,
  ShoppingOutlined,
  SisternodeOutlined,
  SkinOutlined,
  SmileOutlined,
  SolutionOutlined,
  SoundOutlined,
  SplitCellsOutlined,
  StarOutlined,
  SubnodeOutlined,
  SwitcherOutlined,
  SyncOutlined,
  TableOutlined,
  TabletOutlined,
  TagOutlined,
  TagsOutlined,
  TeamOutlined,
  ThunderboltOutlined,
  ToTopOutlined,
  ToolOutlined,
  TrademarkCircleOutlined,
  TrademarkOutlined,
  TransactionOutlined,
  TranslationOutlined,
  TrophyOutlined,
  UngroupOutlined,
  UnlockOutlined,
  UploadOutlined,
  UsbOutlined,
  UserAddOutlined,
  UserDeleteOutlined,
  UserOutlined,
  UserSwitchOutlined,
  UsergroupAddOutlined,
  UsergroupDeleteOutlined,
  VerifiedOutlined,
  VideoCameraAddOutlined,
  VideoCameraOutlined,
  WalletOutlined,
  WhatsAppOutlined,
  WifiOutlined,
  WomanOutlined,
} from '@ant-design/icons';

const iconStyle = {
  fontSize: '20px',
  color: 'black',
};

const Icons = {
  // 方向性图标
  StepBackwardOutlined: <StepBackwardOutlined />,
  StepForwardOutlined: <StepForwardOutlined style={iconStyle} />,
  FastBackwardOutlined: <FastBackwardOutlined style={iconStyle} />,
  FastForwardOutlined: <FastForwardOutlined style={iconStyle} />,
  ShrinkOutlined: <ShrinkOutlined style={iconStyle} />,
  ArrowsAltOutlined: <ArrowsAltOutlined style={iconStyle} />,
  DownOutlined: <DownOutlined style={iconStyle} />,
  UpOutlined: <UpOutlined style={iconStyle} />,
  LeftOutlined: <LeftOutlined style={iconStyle} />,
  RightOutlined: <RightOutlined style={iconStyle} />,
  CaretUpOutlined: <CaretUpOutlined style={iconStyle} />,
  CaretDownOutlined: <CaretDownOutlined style={iconStyle} />,
  CaretLeftOutlined: <CaretLeftOutlined style={iconStyle} />,
  CaretRightOutlined: <CaretRightOutlined style={iconStyle} />,
  UpCircleOutlined: <UpCircleOutlined style={iconStyle} />,
  DownCircleOutlined: <DownCircleOutlined style={iconStyle} />,
  LeftCircleOutlined: <LeftCircleOutlined style={iconStyle} />,
  RightCircleOutlined: <RightCircleOutlined style={iconStyle} />,
  DoubleRightOutlined: <DoubleRightOutlined style={iconStyle} />,
  DoubleLeftOutlined: <DoubleLeftOutlined style={iconStyle} />,
  VerticalLeftOutlined: <VerticalLeftOutlined style={iconStyle} />,
  VerticalRightOutlined: <VerticalRightOutlined style={iconStyle} />,
  VerticalAlignTopOutlined: <VerticalAlignTopOutlined style={iconStyle} />,
  VerticalAlignMiddleOutlined: <VerticalAlignMiddleOutlined style={iconStyle} />,
  VerticalAlignBottomOutlined: <VerticalAlignBottomOutlined style={iconStyle} />,
  ForwardOutlined: <ForwardOutlined style={iconStyle} />,
  BackwardOutlined: <BackwardOutlined style={iconStyle} />,
  RollbackOutlined: <RollbackOutlined style={iconStyle} />,
  EnterOutlined: <EnterOutlined style={iconStyle} />,
  RetweetOutlined: <RetweetOutlined style={iconStyle} />,
  SwapOutlined: <SwapOutlined style={iconStyle} />,
  SwapLeftOutlined: <SwapLeftOutlined style={iconStyle} />,
  SwapRightOutlined: <SwapRightOutlined style={iconStyle} />,
  ArrowUpOutlined: <ArrowUpOutlined style={iconStyle} />,
  ArrowDownOutlined: <ArrowDownOutlined style={iconStyle} />,
  ArrowLeftOutlined: <ArrowLeftOutlined style={iconStyle} />,
  ArrowRightOutlined: <ArrowRightOutlined style={iconStyle} />,
  PlayCircleOutlined: <PlayCircleOutlined style={iconStyle} />,
  UpSquareOutlined: <UpSquareOutlined style={iconStyle} />,
  DownSquareOutlined: <DownSquareOutlined style={iconStyle} />,
  LeftSquareOutlined: <LeftSquareOutlined style={iconStyle} />,
  RightSquareOutlined: <RightSquareOutlined style={iconStyle} />,
  LoginOutlined: <LoginOutlined style={iconStyle} />,
  LogoutOutlined: <LogoutOutlined style={iconStyle} />,
  MenuFoldOutlined: <MenuFoldOutlined style={iconStyle} />,
  MenuUnfoldOutlined: <MenuUnfoldOutlined style={iconStyle} />,
  BorderBottomOutlined: <BorderBottomOutlined style={iconStyle} />,
  BorderHorizontalOutlined: <BorderHorizontalOutlined style={iconStyle} />,
  PicCenterOutlined: <PicCenterOutlined style={iconStyle} />,
  PicLeftOutlined: <PicLeftOutlined style={iconStyle} />,
  PicRightOutlined: <PicRightOutlined style={iconStyle} />,
  FullscreenOutlined: <FullscreenOutlined style={iconStyle} />,
  FullscreenExitOutlined: <FullscreenExitOutlined style={iconStyle} />,
  // 提示建议性图标
  QuestionOutlined: <QuestionOutlined style={iconStyle} />,
  QuestionCircleOutlined: <QuestionCircleOutlined style={iconStyle} />,
  PlusOutlined: <PlusOutlined style={iconStyle} />,
  PlusCircleOutlined: <PlusCircleOutlined style={iconStyle} />,
  PauseOutlined: <PauseOutlined style={iconStyle} />,
  PauseCircleOutlined: <PauseCircleOutlined style={iconStyle} />,
  MinusOutlined: <MinusOutlined style={iconStyle} />,
  MinusCircleOutlined: <MinusCircleOutlined style={iconStyle} />,
  PlusSquareOutlined: <PlusSquareOutlined style={iconStyle} />,
  MinusSquareOutlined: <MinusSquareOutlined style={iconStyle} />,
  InfoOutlined: <InfoOutlined style={iconStyle} />,
  InfoCircleOutlined: <InfoCircleOutlined style={iconStyle} />,
  ExclamationOutlined: <ExclamationOutlined style={iconStyle} />,
  ExclamationCircleOutlined: <ExclamationCircleOutlined style={iconStyle} />,
  CloseOutlined: <CloseOutlined style={iconStyle} />,
  CloseCircleOutlined: <CloseCircleOutlined style={iconStyle} />,
  CloseSquareOutlined: <CloseSquareOutlined style={iconStyle} />,
  CheckOutlined: <CheckOutlined style={iconStyle} />,
  CheckCircleOutlined: <CheckCircleOutlined style={iconStyle} />,
  CheckSquareOutlined: <CheckSquareOutlined style={iconStyle} />,
  ClockCircleOutlined: <ClockCircleOutlined style={iconStyle} />,
  WarningOutlined: <WarningOutlined style={iconStyle} />,
  IssuesCloseOutlined: <IssuesCloseOutlined style={iconStyle} />,
  StopOutlined: <StopOutlined style={iconStyle} />,
  // 编辑类图标
  EditOutlined: <EditOutlined style={iconStyle} />,
  FormOutlined: <FormOutlined style={iconStyle} />,
  CopyOutlined: <CopyOutlined style={iconStyle} />,
  ScissorOutlined: <ScissorOutlined style={iconStyle} />,
  DeleteOutlined: <DeleteOutlined style={iconStyle} />,
  SnippetsOutlined: <SnippetsOutlined style={iconStyle} />,
  DiffOutlined: <DiffOutlined style={iconStyle} />,
  HighlightOutlined: <HighlightOutlined style={iconStyle} />,
  AlignCenterOutlined: <AlignCenterOutlined style={iconStyle} />,
  AlignLeftOutlined: <AlignLeftOutlined style={iconStyle} />,
  AlignRightOutlined: <AlignRightOutlined style={iconStyle} />,
  BgColorsOutlined: <BgColorsOutlined style={iconStyle} />,
  BoldOutlined: <BoldOutlined style={iconStyle} />,
  ItalicOutlined: <ItalicOutlined style={iconStyle} />,
  UnderlineOutlined: <UnderlineOutlined style={iconStyle} />,
  StrikethroughOutlined: <StrikethroughOutlined style={iconStyle} />,
  RedoOutlined: <RedoOutlined style={iconStyle} />,
  UndoOutlined: <UndoOutlined style={iconStyle} />,
  ZoomInOutlined: <ZoomInOutlined style={iconStyle} />,
  ZoomOutOutlined: <ZoomOutOutlined style={iconStyle} />,
  FontColorsOutlined: <FontColorsOutlined style={iconStyle} />,
  FontSizeOutlined: <FontSizeOutlined style={iconStyle} />,
  LineHeightOutlined: <LineHeightOutlined style={iconStyle} />,
  DashOutlined: <DashOutlined style={iconStyle} />,
  SmallDashOutlined: <SmallDashOutlined style={iconStyle} />,
  SortAscendingOutlined: <SortAscendingOutlined style={iconStyle} />,
  SortDescendingOutlined: <SortDescendingOutlined style={iconStyle} />,
  DragOutlined: <DragOutlined style={iconStyle} />,
  OrderedListOutlined: <OrderedListOutlined style={iconStyle} />,
  UnorderedListOutlined: <UnorderedListOutlined style={iconStyle} />,
  RadiusSettingOutlined: <RadiusSettingOutlined style={iconStyle} />,
  ColumnWidthOutlined: <ColumnWidthOutlined style={iconStyle} />,
  ColumnHeightOutlined: <ColumnHeightOutlined style={iconStyle} />,
  // 数据类图标
  AreaChartOutlined: <AreaChartOutlined style={iconStyle} />,
  PieChartOutlined: <PieChartOutlined style={iconStyle} />,
  BarChartOutlined: <BarChartOutlined style={iconStyle} />,
  DotChartOutlined: <DotChartOutlined style={iconStyle} />,
  LineChartOutlined: <LineChartOutlined style={iconStyle} />,
  RadarChartOutlined: <RadarChartOutlined style={iconStyle} />,
  HeatMapOutlined: <HeatMapOutlined style={iconStyle} />,
  FallOutlined: <FallOutlined style={iconStyle} />,
  RiseOutlined: <RiseOutlined style={iconStyle} />,
  StockOutlined: <StockOutlined style={iconStyle} />,
  BoxPlotOutlined: <BoxPlotOutlined style={iconStyle} />,
  FundOutlined: <FundOutlined style={iconStyle} />,
  SlidersOutlined: <SlidersOutlined style={iconStyle} />,
  // 品牌和标识
  AndroidOutlined: <AndroidOutlined style={iconStyle} />,
  AppleOutlined: <AppleOutlined style={iconStyle} />,
  WindowsOutlined: <WindowsOutlined style={iconStyle} />,
  IeOutlined: <IeOutlined style={iconStyle} />,
  ChromeOutlined: <ChromeOutlined style={iconStyle} />,
  GithubOutlined: <GithubOutlined style={iconStyle} />,
  AliwangwangOutlined: <AliwangwangOutlined style={iconStyle} />,
  DingdingOutlined: <DingdingOutlined style={iconStyle} />,
  WeiboSquareOutlined: <WeiboSquareOutlined style={iconStyle} />,
  WeiboCircleOutlined: <WeiboCircleOutlined style={iconStyle} />,
  TaobaoCircleOutlined: <TaobaoCircleOutlined style={iconStyle} />,
  Html5Outlined: <Html5Outlined style={iconStyle} />,
  WeiboOutlined: <WeiboOutlined style={iconStyle} />,
  TwitterOutlined: <TwitterOutlined style={iconStyle} />,
  WechatOutlined: <WechatOutlined style={iconStyle} />,
  YoutubeOutlined: <YoutubeOutlined style={iconStyle} />,
  AlipayCircleOutlined: <AlipayCircleOutlined style={iconStyle} />,
  TaobaoOutlined: <TaobaoOutlined style={iconStyle} />,
  SkypeOutlined: <SkypeOutlined style={iconStyle} />,
  QqOutlined: <QqOutlined style={iconStyle} />,
  MediumWorkmarkOutlined: <MediumWorkmarkOutlined style={iconStyle} />,
  GitlabOutlined: <GitlabOutlined style={iconStyle} />,
  MediumOutlined: <MediumOutlined style={iconStyle} />,
  LinkedinOutlined: <LinkedinOutlined style={iconStyle} />,
  GooglePlusOutlined: <GooglePlusOutlined style={iconStyle} />,
  DropboxOutlined: <DropboxOutlined style={iconStyle} />,
  FacebookOutlined: <FacebookOutlined style={iconStyle} />,
  CodepenOutlined: <CodepenOutlined style={iconStyle} />,
  CodeSandboxOutlined: <CodeSandboxOutlined style={iconStyle} />,
  AmazonOutlined: <AmazonOutlined style={iconStyle} />,
  GoogleOutlined: <GoogleOutlined style={iconStyle} />,
  CodepenCircleOutlined: <CodepenCircleOutlined style={iconStyle} />,
  AlipayOutlined: <AlipayOutlined style={iconStyle} />,
  AntDesignOutlined: <AntDesignOutlined style={iconStyle} />,
  AntCloudOutlined: <AntCloudOutlined style={iconStyle} />,
  AliyunOutlined: <AliyunOutlined style={iconStyle} />,
  ZhihuOutlined: <ZhihuOutlined style={iconStyle} />,
  SlackOutlined: <SlackOutlined style={iconStyle} />,
  SlackSquareOutlined: <SlackSquareOutlined style={iconStyle} />,
  BehanceOutlined: <BehanceOutlined style={iconStyle} />,
  BehanceSquareOutlined: <BehanceSquareOutlined style={iconStyle} />,
  DribbbleOutlined: <DribbbleOutlined style={iconStyle} />,
  DribbbleSquareOutlined: <DribbbleSquareOutlined style={iconStyle} />,
  InstagramOutlined: <InstagramOutlined style={iconStyle} />,
  YuqueOutlined: <YuqueOutlined style={iconStyle} />,
  AlibabaOutlined: <AlibabaOutlined style={iconStyle} />,
  YahooOutlined: <YahooOutlined style={iconStyle} />,
  RedditOutlined: <RedditOutlined style={iconStyle} />,
  SketchOutlined: <SketchOutlined style={iconStyle} />,
  //网站通用图标
  AccountBookOutlined: <AccountBookOutlined style={iconStyle} />,
  AimOutlined: <AimOutlined style={iconStyle} />,
  AlertOutlined: <AlertOutlined style={iconStyle} />,
  ApartmentOutlined: <ApartmentOutlined style={iconStyle} />,
  ApiOutlined: <ApiOutlined style={iconStyle} />,
  AppstoreAddOutlined: <AppstoreAddOutlined style={iconStyle} />,
  AppstoreOutlined: <AppstoreOutlined style={iconStyle} />,
  AudioOutlined: <AudioOutlined style={iconStyle} />,
  AudioMutedOutlined: <AudioMutedOutlined style={iconStyle} />,
  AuditOutlined: <AuditOutlined style={iconStyle} />,
  BankOutlined: <BankOutlined style={iconStyle} />,
  BarcodeOutlined: <BarcodeOutlined style={iconStyle} />,
  BarsOutlined: <BarsOutlined style={iconStyle} />,
  BellOutlined: <BellOutlined style={iconStyle} />,
  BlockOutlined: <BlockOutlined style={iconStyle} />,
  BookOutlined: <BookOutlined style={iconStyle} />,
  BorderOutlined: <BorderOutlined style={iconStyle} />,
  BorderlessTableOutlined: <BorderlessTableOutlined style={iconStyle} />,
  BranchesOutlined: <BranchesOutlined style={iconStyle} />,
  BugOutlined: <BugOutlined style={iconStyle} />,
  BuildOutlined: <BuildOutlined style={iconStyle} />,
  BulbOutlined: <BulbOutlined style={iconStyle} />,
  CalculatorOutlined: <CalculatorOutlined style={iconStyle} />,
  CalendarOutlined: <CalendarOutlined style={iconStyle} />,
  CameraOutlined: <CameraOutlined style={iconStyle} />,
  CarOutlined: <CarOutlined style={iconStyle} />,
  CarryOutOutlined: <CarryOutOutlined style={iconStyle} />,
  CiCircleOutlined: <CiCircleOutlined style={iconStyle} />,
  CiOutlined: <CiOutlined style={iconStyle} />,
  ClearOutlined: <ClearOutlined style={iconStyle} />,
  CloudDownloadOutlined: <CloudDownloadOutlined style={iconStyle} />,
  CloudOutlined: <CloudOutlined style={iconStyle} />,
  CloudServerOutlined: <CloudServerOutlined style={iconStyle} />,
  CloudSyncOutlined: <CloudSyncOutlined style={iconStyle} />,
  CloudUploadOutlined: <CloudUploadOutlined style={iconStyle} />,
  ClusterOutlined: <ClusterOutlined style={iconStyle} />,
  CodeOutlined: <CodeOutlined style={iconStyle} />,
  CoffeeOutlined: <CoffeeOutlined style={iconStyle} />,
  CommentOutlined: <CommentOutlined style={iconStyle} />,
  CompassOutlined: <CompassOutlined style={iconStyle} />,
  CompressOutlined: <CompressOutlined style={iconStyle} />,
  ConsoleSqlOutlined: <ConsoleSqlOutlined style={iconStyle} />,
  ContactsOutlined: <ContactsOutlined style={iconStyle} />,
  ContainerOutlined: <ContainerOutlined style={iconStyle} />,
  ControlOutlined: <ControlOutlined style={iconStyle} />,
  CopyrightOutlined: <CopyrightOutlined style={iconStyle} />,
  CreditCardOutlined: <CreditCardOutlined style={iconStyle} />,
  CrownOutlined: <CrownOutlined style={iconStyle} />,
  CustomerServiceOutlined: <CustomerServiceOutlined style={iconStyle} />,
  DashboardOutlined: <DashboardOutlined style={iconStyle} />,
  DatabaseOutlined: <DatabaseOutlined style={iconStyle} />,
  DeleteColumnOutlined: <DeleteColumnOutlined style={iconStyle} />,
  DeleteRowOutlined: <DeleteRowOutlined style={iconStyle} />,
  DeliveredProcedureOutlined: <DeliveredProcedureOutlined style={iconStyle} />,
  DeploymentUnitOutlined: <DeploymentUnitOutlined style={iconStyle} />,
  DesktopOutlined: <DesktopOutlined style={iconStyle} />,
  DingtalkOutlined: <DingtalkOutlined style={iconStyle} />,
  DisconnectOutlined: <DisconnectOutlined style={iconStyle} />,
  DislikeOutlined: <DislikeOutlined style={iconStyle} />,
  DollarCircleOutlined: <DollarCircleOutlined style={iconStyle} />,
  DollarOutlined: <DollarOutlined style={iconStyle} />,
  DownloadOutlined: <DownloadOutlined style={iconStyle} />,
  EllipsisOutlined: <EllipsisOutlined style={iconStyle} />,
  EnvironmentOutlined: <EnvironmentOutlined style={iconStyle} />,
  EuroCircleOutlined: <EuroCircleOutlined style={iconStyle} />,
  EuroOutlined: <EuroOutlined style={iconStyle} />,
  ExceptionOutlined: <ExceptionOutlined style={iconStyle} />,
  ExpandAltOutlined: <ExpandAltOutlined style={iconStyle} />,
  ExpandOutlined: <ExpandOutlined style={iconStyle} />,
  ExperimentOutlined: <ExperimentOutlined style={iconStyle} />,
  ExportOutlined: <ExportOutlined style={iconStyle} />,
  EyeOutlined: <EyeOutlined style={iconStyle} />,
  EyeInvisibleOutlined: <EyeInvisibleOutlined style={iconStyle} />,
  FieldBinaryOutlined: <FieldBinaryOutlined style={iconStyle} />,
  FieldNumberOutlined: <FieldNumberOutlined style={iconStyle} />,
  FieldStringOutlined: <FieldStringOutlined style={iconStyle} />,
  FieldTimeOutlined: <FieldTimeOutlined style={iconStyle} />,
  FileAddOutlined: <FileAddOutlined style={iconStyle} />,
  FileDoneOutlined: <FileDoneOutlined style={iconStyle} />,
  FileExcelOutlined: <FileExcelOutlined style={iconStyle} />,
  FileExclamationOutlined: <FileExclamationOutlined style={iconStyle} />,
  FileOutlined: <FileOutlined style={iconStyle} />,
  FileGifOutlined: <FileGifOutlined style={iconStyle} />,
  FileImageOutlined: <FileImageOutlined style={iconStyle} />,
  FileJpgOutlined: <FileJpgOutlined style={iconStyle} />,
  FileMarkdownOutlined: <FileMarkdownOutlined style={iconStyle} />,
  FilePdfOutlined: <FilePdfOutlined style={iconStyle} />,
  FilePptOutlined: <FilePptOutlined style={iconStyle} />,
  FileProtectOutlined: <FileProtectOutlined style={iconStyle} />,
  FileSearchOutlined: <FileSearchOutlined style={iconStyle} />,
  FileSyncOutlined: <FileSyncOutlined style={iconStyle} />,
  FileTextOutlined: <FileTextOutlined style={iconStyle} />,
  FileUnknownOutlined: <FileUnknownOutlined style={iconStyle} />,
  FileWordOutlined: <FileWordOutlined style={iconStyle} />,
  FileZipOutlined: <FileZipOutlined style={iconStyle} />,
  FilterOutlined: <FilterOutlined style={iconStyle} />,
  FireOutlined: <FireOutlined style={iconStyle} />,
  FlagOutlined: <FlagOutlined style={iconStyle} />,
  FolderAddOutlined: <FolderAddOutlined style={iconStyle} />,
  FolderOutlined: <FolderOutlined style={iconStyle} />,
  FolderOpenOutlined: <FolderOpenOutlined style={iconStyle} />,
  FolderViewOutlined: <FolderViewOutlined style={iconStyle} />,
  ForkOutlined: <ForkOutlined style={iconStyle} />,
  FormatPainterOutlined: <FormatPainterOutlined style={iconStyle} />,
  FrownOutlined: <FrownOutlined style={iconStyle} />,
  FunctionOutlined: <FunctionOutlined style={iconStyle} />,
  FundProjectionScreenOutlined: <FundProjectionScreenOutlined style={iconStyle} />,
  FundViewOutlined: <FundViewOutlined style={iconStyle} />,
  FunnelPlotOutlined: <FunnelPlotOutlined style={iconStyle} />,
  GatewayOutlined: <GatewayOutlined style={iconStyle} />,
  GifOutlined: <GifOutlined style={iconStyle} />,
  GiftOutlined: <GiftOutlined style={iconStyle} />,
  GlobalOutlined: <GlobalOutlined style={iconStyle} />,
  GoldOutlined: <GoldOutlined style={iconStyle} />,
  GroupOutlined: <GroupOutlined style={iconStyle} />,
  HddOutlined: <HddOutlined style={iconStyle} />,
  HeartOutlined: <HeartOutlined style={iconStyle} />,
  HistoryOutlined: <HistoryOutlined style={iconStyle} />,
  HomeOutlined: <HomeOutlined style={iconStyle} />,
  HourglassOutlined: <HourglassOutlined style={iconStyle} />,
  IdcardOutlined: <IdcardOutlined style={iconStyle} />,
  ImportOutlined: <ImportOutlined style={iconStyle} />,
  InboxOutlined: <InboxOutlined style={iconStyle} />,
  InsertRowAboveOutlined: <InsertRowAboveOutlined style={iconStyle} />,
  InsertRowBelowOutlined: <InsertRowBelowOutlined style={iconStyle} />,
  InsertRowLeftOutlined: <InsertRowLeftOutlined style={iconStyle} />,
  InsertRowRightOutlined: <InsertRowRightOutlined style={iconStyle} />,
  InsuranceOutlined: <InsuranceOutlined style={iconStyle} />,
  InteractionOutlined: <InteractionOutlined style={iconStyle} />,
  KeyOutlined: <KeyOutlined style={iconStyle} />,
  LaptopOutlined: <LaptopOutlined style={iconStyle} />,
  LayoutOutlined: <LayoutOutlined style={iconStyle} />,
  LikeOutlined: <LikeOutlined style={iconStyle} />,
  LineOutlined: <LineOutlined style={iconStyle} />,
  LinkOutlined: <LinkOutlined style={iconStyle} />,
  Loading3QuartersOutlined: <Loading3QuartersOutlined style={iconStyle} />,
  LoadingOutlined: <LoadingOutlined style={iconStyle} />,
  LockOutlined: <LockOutlined style={iconStyle} />,
  MacCommandOutlined: <MacCommandOutlined style={iconStyle} />,
  MailOutlined: <MailOutlined style={iconStyle} />,
  ManOutlined: <ManOutlined style={iconStyle} />,
  MedicineBoxOutlined: <MedicineBoxOutlined style={iconStyle} />,
  MehOutlined: <MehOutlined style={iconStyle} />,
  MenuOutlined: <MenuOutlined style={iconStyle} />,
  MergeCellsOutlined: <MergeCellsOutlined style={iconStyle} />,
  MessageOutlined: <MessageOutlined style={iconStyle} />,
  MobileOutlined: <MobileOutlined style={iconStyle} />,
  MoneyCollectOutlined: <MoneyCollectOutlined style={iconStyle} />,
  MonitorOutlined: <MonitorOutlined style={iconStyle} />,
  MoreOutlined: <MoreOutlined style={iconStyle} />,
  NodeCollapseOutlined: <NodeCollapseOutlined style={iconStyle} />,
  NodeExpandOutlined: <NodeExpandOutlined style={iconStyle} />,
  NodeIndexOutlined: <NodeIndexOutlined style={iconStyle} />,
  NotificationOutlined: <NotificationOutlined style={iconStyle} />,
  NumberOutlined: <NumberOutlined style={iconStyle} />,
  OneToOneOutlined: <OneToOneOutlined style={iconStyle} />,
  PaperClipOutlined: <PaperClipOutlined style={iconStyle} />,
  PartitionOutlined: <PartitionOutlined style={iconStyle} />,
  PayCircleOutlined: <PayCircleOutlined style={iconStyle} />,
  PercentageOutlined: <PercentageOutlined style={iconStyle} />,
  PhoneOutlined: <PhoneOutlined style={iconStyle} />,
  PictureOutlined: <PictureOutlined style={iconStyle} />,
  PlaySquareOutlined: <PlaySquareOutlined style={iconStyle} />,
  PoundCircleOutlined: <PoundCircleOutlined style={iconStyle} />,
  PoundOutlined: <PoundOutlined style={iconStyle} />,
  PoweroffOutlined: <PoweroffOutlined style={iconStyle} />,
  PrinterOutlined: <PrinterOutlined style={iconStyle} />,
  ProfileOutlined: <ProfileOutlined style={iconStyle} />,
  ProjectOutlined: <ProjectOutlined style={iconStyle} />,
  PropertySafetyOutlined: <PropertySafetyOutlined style={iconStyle} />,
  PullRequestOutlined: <PullRequestOutlined style={iconStyle} />,
  PushpinOutlined: <PushpinOutlined style={iconStyle} />,
  QrcodeOutlined: <QrcodeOutlined style={iconStyle} />,
  ReadOutlined: <ReadOutlined style={iconStyle} />,
  ReconciliationOutlined: <ReconciliationOutlined style={iconStyle} />,
  RedEnvelopeOutlined: <RedEnvelopeOutlined style={iconStyle} />,
  ReloadOutlined: <ReloadOutlined style={iconStyle} />,
  RestOutlined: <RestOutlined style={iconStyle} />,
  RobotOutlined: <RobotOutlined style={iconStyle} />,
  RocketOutlined: <RocketOutlined style={iconStyle} />,
  RotateLeftOutlined: <RotateLeftOutlined style={iconStyle} />,
  RotateRightOutlined: <RotateRightOutlined style={iconStyle} />,
  SafetyCertificateOutlined: <SafetyCertificateOutlined style={iconStyle} />,
  SafetyOutlined: <SafetyOutlined style={iconStyle} />,
  SaveOutlined: <SaveOutlined style={iconStyle} />,
  ScanOutlined: <ScanOutlined style={iconStyle} />,
  ScheduleOutlined: <ScheduleOutlined style={iconStyle} />,
  SearchOutlined: <SearchOutlined style={iconStyle} />,
  SecurityScanOutlined: <SecurityScanOutlined style={iconStyle} />,
  SelectOutlined: <SelectOutlined style={iconStyle} />,
  SendOutlined: <SendOutlined style={iconStyle} />,
  SettingOutlined: <SettingOutlined style={iconStyle} />,
  ShakeOutlined: <ShakeOutlined style={iconStyle} />,
  ShareAltOutlined: <ShareAltOutlined style={iconStyle} />,
  ShopOutlined: <ShopOutlined style={iconStyle} />,
  ShoppingCartOutlined: <ShoppingCartOutlined style={iconStyle} />,
  ShoppingOutlined: <ShoppingOutlined style={iconStyle} />,
  SisternodeOutlined: <SisternodeOutlined style={iconStyle} />,
  SkinOutlined: <SkinOutlined style={iconStyle} />,
  SmileOutlined: <SmileOutlined style={iconStyle} />,
  SolutionOutlined: <SolutionOutlined style={iconStyle} />,
  SoundOutlined: <SoundOutlined style={iconStyle} />,
  SplitCellsOutlined: <SplitCellsOutlined style={iconStyle} />,
  StarOutlined: <StarOutlined style={iconStyle} />,
  SubnodeOutlined: <SubnodeOutlined style={iconStyle} />,
  SwitcherOutlined: <SwitcherOutlined style={iconStyle} />,
  SyncOutlined: <SyncOutlined style={iconStyle} />,
  TableOutlined: <TableOutlined style={iconStyle} />,
  TabletOutlined: <TabletOutlined style={iconStyle} />,
  TagOutlined: <TagOutlined style={iconStyle} />,
  TagsOutlined: <TagsOutlined style={iconStyle} />,
  TeamOutlined: <TeamOutlined style={iconStyle} />,
  ThunderboltOutlined: <ThunderboltOutlined style={iconStyle} />,
  ToTopOutlined: <ToTopOutlined style={iconStyle} />,
  ToolOutlined: <ToolOutlined style={iconStyle} />,
  TrademarkCircleOutlined: <TrademarkCircleOutlined style={iconStyle} />,
  TrademarkOutlined: <TrademarkOutlined style={iconStyle} />,
  TransactionOutlined: <TransactionOutlined style={iconStyle} />,
  TranslationOutlined: <TranslationOutlined style={iconStyle} />,
  TrophyOutlined: <TrophyOutlined style={iconStyle} />,
  UngroupOutlined: <UngroupOutlined style={iconStyle} />,
  UnlockOutlined: <UnlockOutlined style={iconStyle} />,
  UploadOutlined: <UploadOutlined style={iconStyle} />,
  UsbOutlined: <UsbOutlined style={iconStyle} />,
  UserAddOutlined: <UserAddOutlined style={iconStyle} />,
  UserDeleteOutlined: <UserDeleteOutlined style={iconStyle} />,
  UserOutlined: <UserOutlined style={iconStyle} />,
  UserSwitchOutlined: <UserSwitchOutlined style={iconStyle} />,
  UsergroupAddOutlined: <UsergroupAddOutlined style={iconStyle} />,
  UsergroupDeleteOutlined: <UsergroupDeleteOutlined style={iconStyle} />,
  VerifiedOutlined: <VerifiedOutlined style={iconStyle} />,
  VideoCameraAddOutlined: <VideoCameraAddOutlined style={iconStyle} />,
  VideoCameraOutlined: <VideoCameraOutlined style={iconStyle} />,
  WalletOutlined: <WalletOutlined style={iconStyle} />,
  WhatsAppOutlined: <WhatsAppOutlined style={iconStyle} />,
  WifiOutlined: <WifiOutlined style={iconStyle} />,
  WomanOutlined: <WomanOutlined style={iconStyle} />,
};

export default Icons;
