import React from 'react';
import {
  StepBackwardOutlined,
  StepForwardOutlined,
  FastBackwardOutlined,
  FastForwardOutlined,
  ShrinkOutlined,
  ArrowsAltOutlined,
  DownOutlined,
  UpOutlined,
  LeftOutlined,
  RightOutlined,
  CaretUpOutlined,
  CaretDownOutlined,
  CaretLeftOutlined,
  CaretRightOutlined,
  UpCircleOutlined,
  DownCircleOutlined,
  LeftCircleOutlined,
  RightCircleOutlined,
  DoubleRightOutlined,
  DoubleLeftOutlined,
  VerticalLeftOutlined,
  VerticalRightOutlined,
  VerticalAlignTopOutlined,
  VerticalAlignMiddleOutlined,
  VerticalAlignBottomOutlined,
  ForwardOutlined,
  BackwardOutlined,
  RollbackOutlined,
  EnterOutlined,
  RetweetOutlined,
  SwapOutlined,
  SwapLeftOutlined,
  SwapRightOutlined,
  ArrowUpOutlined,
  ArrowDownOutlined,
  ArrowLeftOutlined,
  ArrowRightOutlined,
  PlayCircleOutlined,
  UpSquareOutlined,
  DownSquareOutlined,
  LeftSquareOutlined,
  RightSquareOutlined,
  LoginOutlined,
  LogoutOutlined,
  MenuFoldOutlined,
  MenuUnfoldOutlined,
  BorderBottomOutlined,
  BorderHorizontalOutlined,
  PicCenterOutlined,
  PicLeftOutlined,
  PicRightOutlined,
  FullscreenOutlined,
  FullscreenExitOutlined,
  QuestionOutlined,
  QuestionCircleOutlined,
  PlusOutlined,
  PlusCircleOutlined,
  PauseOutlined,
  PauseCircleOutlined,
  MinusOutlined,
  MinusCircleOutlined,
  PlusSquareOutlined,
  MinusSquareOutlined,
  InfoOutlined,
  InfoCircleOutlined,
  ExclamationOutlined,
  ExclamationCircleOutlined,
  CloseOutlined,
  CloseCircleOutlined,
  CloseSquareOutlined,
  CheckOutlined,
  CheckCircleOutlined,
  CheckSquareOutlined,
  ClockCircleOutlined,
  WarningOutlined,
  IssuesCloseOutlined,
  StopOutlined,
  EditOutlined,
  FormOutlined,
  CopyOutlined,
  ScissorOutlined,
  DeleteOutlined,
  SnippetsOutlined,
  DiffOutlined,
  HighlightOutlined,
  AlignCenterOutlined,
  AlignLeftOutlined,
  AlignRightOutlined,
  BgColorsOutlined,
  BoldOutlined,
  ItalicOutlined,
  UnderlineOutlined,
  StrikethroughOutlined,
  RedoOutlined,
  UndoOutlined,
  ZoomInOutlined,
  ZoomOutOutlined,
  FontColorsOutlined,
  FontSizeOutlined,
  LineHeightOutlined,
  DashOutlined,
  SmallDashOutlined,
  SortAscendingOutlined,
  SortDescendingOutlined,
  DragOutlined,
  OrderedListOutlined,
  UnorderedListOutlined,
  RadiusSettingOutlined,
  ColumnWidthOutlined,
  ColumnHeightOutlined,
  AreaChartOutlined,
  PieChartOutlined,
  BarChartOutlined,
  DotChartOutlined,
  LineChartOutlined,
  RadarChartOutlined,
  HeatMapOutlined,
  FallOutlined,
  RiseOutlined,
  StockOutlined,
  BoxPlotOutlined,
  FundOutlined,
  SlidersOutlined,
  AndroidOutlined,
  AppleOutlined,
  WindowsOutlined,
  IeOutlined,
  ChromeOutlined,
  GithubOutlined,
  AliwangwangOutlined,
  DingdingOutlined,
  WeiboSquareOutlined,
  WeiboCircleOutlined,
  TaobaoCircleOutlined,
  Html5Outlined,
  WeiboOutlined,
  TwitterOutlined,
  WechatOutlined,
  YoutubeOutlined,
  AlipayCircleOutlined,
  TaobaoOutlined,
  SkypeOutlined,
  QqOutlined,
  MediumWorkmarkOutlined,
  GitlabOutlined,
  MediumOutlined,
  LinkedinOutlined,
  GooglePlusOutlined,
  DropboxOutlined,
  FacebookOutlined,
  CodepenOutlined,
  CodeSandboxOutlined,
  AmazonOutlined,
  GoogleOutlined,
  CodepenCircleOutlined,
  AlipayOutlined,
  AntDesignOutlined,
  AntCloudOutlined,
  AliyunOutlined,
  ZhihuOutlined,
  SlackOutlined,
  SlackSquareOutlined,
  BehanceOutlined,
  BehanceSquareOutlined,
  DribbbleOutlined,
  DribbbleSquareOutlined,
  InstagramOutlined,
  YuqueOutlined,
  AlibabaOutlined,
  YahooOutlined,
  RedditOutlined,
  SketchOutlined,
  AccountBookOutlined,
  AimOutlined,
  AlertOutlined,
  ApartmentOutlined,
  ApiOutlined,
  AppstoreAddOutlined,
  AppstoreOutlined,
  AudioOutlined,
  AudioMutedOutlined,
  AuditOutlined,
  BankOutlined,
  BarcodeOutlined,
  BarsOutlined,
  BellOutlined,
  BlockOutlined,
  BookOutlined,
  BorderOutlined,
  BorderlessTableOutlined,
  BranchesOutlined,
  BugOutlined,
  BuildOutlined,
  BulbOutlined,
  CalculatorOutlined,
  CalendarOutlined,
  CameraOutlined,
  CarOutlined,
  CarryOutOutlined,
  CiCircleOutlined,
  CiOutlined,
  ClearOutlined,
  CloudDownloadOutlined,
  CloudOutlined,
  CloudServerOutlined,
  CloudSyncOutlined,
  CloudUploadOutlined,
  ClusterOutlined,
  CodeOutlined,
  CoffeeOutlined,
  CommentOutlined,
  CompassOutlined,
  CompressOutlined,
  ConsoleSqlOutlined,
  ContactsOutlined,
  ContainerOutlined,
  ControlOutlined,
  CopyrightOutlined,
  CreditCardOutlined,
  CrownOutlined,
  CustomerServiceOutlined,
  DashboardOutlined,
  DatabaseOutlined,
  DeleteColumnOutlined,
  DeleteRowOutlined,
  DeliveredProcedureOutlined,
  DeploymentUnitOutlined,
  DesktopOutlined,
  DingtalkOutlined,
  DisconnectOutlined,
  DislikeOutlined,
  DollarCircleOutlined,
  DollarOutlined,
  DownloadOutlined,
  EllipsisOutlined,
  EnvironmentOutlined,
  EuroCircleOutlined,
  EuroOutlined,
  ExceptionOutlined,
  ExpandAltOutlined,
  ExpandOutlined,
  ExperimentOutlined,
  ExportOutlined,
  EyeOutlined,
  EyeInvisibleOutlined,
  FieldBinaryOutlined,
  FieldNumberOutlined,
  FieldStringOutlined,
  FieldTimeOutlined,
  FileAddOutlined,
  FileDoneOutlined,
  FileExcelOutlined,
  FileExclamationOutlined,
  FileOutlined,
  FileGifOutlined,
  FileImageOutlined,
  FileJpgOutlined,
  FileMarkdownOutlined,
  FilePdfOutlined,
  FilePptOutlined,
  FileProtectOutlined,
  FileSearchOutlined,
  FileSyncOutlined,
  FileTextOutlined,
  FileUnknownOutlined,
  FileWordOutlined,
  FileZipOutlined,
  FilterOutlined,
  FireOutlined,
  FlagOutlined,
  FolderAddOutlined,
  FolderOutlined,
  FolderOpenOutlined,
  FolderViewOutlined,
  ForkOutlined,
  FormatPainterOutlined,
  FrownOutlined,
  FunctionOutlined,
  FundProjectionScreenOutlined,
  FundViewOutlined,
  FunnelPlotOutlined,
  GatewayOutlined,
  GifOutlined,
  GiftOutlined,
  GlobalOutlined,
  GoldOutlined,
  GroupOutlined,
  HddOutlined,
  HeartOutlined,
  HistoryOutlined,
  HomeOutlined,
  HourglassOutlined,
  IdcardOutlined,
  ImportOutlined,
  InboxOutlined,
  InsertRowAboveOutlined,
  InsertRowBelowOutlined,
  InsertRowLeftOutlined,
  InsertRowRightOutlined,
  InsuranceOutlined,
  InteractionOutlined,
  KeyOutlined,
  LaptopOutlined,
  LayoutOutlined,
  LikeOutlined,
  LineOutlined,
  LinkOutlined,
  Loading3QuartersOutlined,
  LoadingOutlined,
  LockOutlined,
  MacCommandOutlined,
  MailOutlined,
  ManOutlined,
  MedicineBoxOutlined,
  MehOutlined,
  MenuOutlined,
  MergeCellsOutlined,
  MessageOutlined,
  MobileOutlined,
  MoneyCollectOutlined,
  MonitorOutlined,
  MoreOutlined,
  NodeCollapseOutlined,
  NodeExpandOutlined,
  NodeIndexOutlined,
  NotificationOutlined,
  NumberOutlined,
  OneToOneOutlined,
  PaperClipOutlined,
  PartitionOutlined,
  PayCircleOutlined,
  PercentageOutlined,
  PhoneOutlined,
  PictureOutlined,
  PlaySquareOutlined,
  PoundCircleOutlined,
  PoundOutlined,
  PoweroffOutlined,
  PrinterOutlined,
  ProfileOutlined,
  ProjectOutlined,
  PropertySafetyOutlined,
  PullRequestOutlined,
  PushpinOutlined,
  QrcodeOutlined,
  ReadOutlined,
  ReconciliationOutlined,
  RedEnvelopeOutlined,
  ReloadOutlined,
  RestOutlined,
  RobotOutlined,
  RocketOutlined,
  RotateLeftOutlined,
  RotateRightOutlined,
  SafetyCertificateOutlined,
  SafetyOutlined,
  SaveOutlined,
  ScanOutlined,
  ScheduleOutlined,
  SearchOutlined,
  SecurityScanOutlined,
  SelectOutlined,
  SendOutlined,
  SettingOutlined,
  ShakeOutlined,
  ShareAltOutlined,
  ShopOutlined,
  ShoppingCartOutlined,
  ShoppingOutlined,
  SisternodeOutlined,
  SkinOutlined,
  SmileOutlined,
  SolutionOutlined,
  SoundOutlined,
  SplitCellsOutlined,
  StarOutlined,
  SubnodeOutlined,
  SwitcherOutlined,
  SyncOutlined,
  TableOutlined,
  TabletOutlined,
  TagOutlined,
  TagsOutlined,
  TeamOutlined,
  ThunderboltOutlined,
  ToTopOutlined,
  ToolOutlined,
  TrademarkCircleOutlined,
  TrademarkOutlined,
  TransactionOutlined,
  TranslationOutlined,
  TrophyOutlined,
  UngroupOutlined,
  UnlockOutlined,
  UploadOutlined,
  UsbOutlined,
  UserAddOutlined,
  UserDeleteOutlined,
  UserOutlined,
  UserSwitchOutlined,
  UsergroupAddOutlined,
  UsergroupDeleteOutlined,
  VerifiedOutlined,
  VideoCameraAddOutlined,
  VideoCameraOutlined,
  WalletOutlined,
  WhatsAppOutlined,
  WifiOutlined,
  WomanOutlined,
} from '@ant-design/icons';

const iconEnum = {
  // 方向性图标
  StepBackwardOutlined: <StepBackwardOutlined />,
  StepForwardOutlined: <StepForwardOutlined />,
  FastBackwardOutlined: <FastBackwardOutlined />,
  FastForwardOutlined: <FastForwardOutlined />,
  ShrinkOutlined: <ShrinkOutlined />,
  ArrowsAltOutlined: <ArrowsAltOutlined />,
  DownOutlined: <DownOutlined />,
  UpOutlined: <UpOutlined />,
  LeftOutlined: <LeftOutlined />,
  RightOutlined: <RightOutlined />,
  CaretUpOutlined: <CaretUpOutlined />,
  CaretDownOutlined: <CaretDownOutlined />,
  CaretLeftOutlined: <CaretLeftOutlined />,
  CaretRightOutlined: <CaretRightOutlined />,
  UpCircleOutlined: <UpCircleOutlined />,
  DownCircleOutlined: <DownCircleOutlined />,
  LeftCircleOutlined: <LeftCircleOutlined />,
  RightCircleOutlined: <RightCircleOutlined />,
  DoubleRightOutlined: <DoubleRightOutlined />,
  DoubleLeftOutlined: <DoubleLeftOutlined />,
  VerticalLeftOutlined: <VerticalLeftOutlined />,
  VerticalRightOutlined: <VerticalRightOutlined />,
  VerticalAlignTopOutlined: <VerticalAlignTopOutlined />,
  VerticalAlignMiddleOutlined: <VerticalAlignMiddleOutlined />,
  VerticalAlignBottomOutlined: <VerticalAlignBottomOutlined />,
  ForwardOutlined: <ForwardOutlined />,
  BackwardOutlined: <BackwardOutlined />,
  RollbackOutlined: <RollbackOutlined />,
  EnterOutlined: <EnterOutlined />,
  RetweetOutlined: <RetweetOutlined />,
  SwapOutlined: <SwapOutlined />,
  SwapLeftOutlined: <SwapLeftOutlined />,
  SwapRightOutlined: <SwapRightOutlined />,
  ArrowUpOutlined: <ArrowUpOutlined />,
  ArrowDownOutlined: <ArrowDownOutlined />,
  ArrowLeftOutlined: <ArrowLeftOutlined />,
  ArrowRightOutlined: <ArrowRightOutlined />,
  PlayCircleOutlined: <PlayCircleOutlined />,
  UpSquareOutlined: <UpSquareOutlined />,
  DownSquareOutlined: <DownSquareOutlined />,
  LeftSquareOutlined: <LeftSquareOutlined />,
  RightSquareOutlined: <RightSquareOutlined />,
  LoginOutlined: <LoginOutlined />,
  LogoutOutlined: <LogoutOutlined />,
  MenuFoldOutlined: <MenuFoldOutlined />,
  MenuUnfoldOutlined: <MenuUnfoldOutlined />,
  BorderBottomOutlined: <BorderBottomOutlined />,
  BorderHorizontalOutlined: <BorderHorizontalOutlined />,
  PicCenterOutlined: <PicCenterOutlined />,
  PicLeftOutlined: <PicLeftOutlined />,
  PicRightOutlined: <PicRightOutlined />,
  FullscreenOutlined: <FullscreenOutlined />,
  FullscreenExitOutlined: <FullscreenExitOutlined />,
  // 提示建议性图标
  QuestionOutlined: <QuestionOutlined />,
  QuestionCircleOutlined: <QuestionCircleOutlined />,
  PlusOutlined: <PlusOutlined />,
  PlusCircleOutlined: <PlusCircleOutlined />,
  PauseOutlined: <PauseOutlined />,
  PauseCircleOutlined: <PauseCircleOutlined />,
  MinusOutlined: <MinusOutlined />,
  MinusCircleOutlined: <MinusCircleOutlined />,
  PlusSquareOutlined: <PlusSquareOutlined />,
  MinusSquareOutlined: <MinusSquareOutlined />,
  InfoOutlined: <InfoOutlined />,
  InfoCircleOutlined: <InfoCircleOutlined />,
  ExclamationOutlined: <ExclamationOutlined />,
  ExclamationCircleOutlined: <ExclamationCircleOutlined />,
  CloseOutlined: <CloseOutlined />,
  CloseCircleOutlined: <CloseCircleOutlined />,
  CloseSquareOutlined: <CloseSquareOutlined />,
  CheckOutlined: <CheckOutlined />,
  CheckCircleOutlined: <CheckCircleOutlined />,
  CheckSquareOutlined: <CheckSquareOutlined />,
  ClockCircleOutlined: <ClockCircleOutlined />,
  WarningOutlined: <WarningOutlined />,
  IssuesCloseOutlined: <IssuesCloseOutlined />,
  StopOutlined: <StopOutlined />,
  // 编辑类图标
  EditOutlined: <EditOutlined />,
  FormOutlined: <FormOutlined />,
  CopyOutlined: <CopyOutlined />,
  ScissorOutlined: <ScissorOutlined />,
  DeleteOutlined: <DeleteOutlined />,
  SnippetsOutlined: <SnippetsOutlined />,
  DiffOutlined: <DiffOutlined />,
  HighlightOutlined: <HighlightOutlined />,
  AlignCenterOutlined: <AlignCenterOutlined />,
  AlignLeftOutlined: <AlignLeftOutlined />,
  AlignRightOutlined: <AlignRightOutlined />,
  BgColorsOutlined: <BgColorsOutlined />,
  BoldOutlined: <BoldOutlined />,
  ItalicOutlined: <ItalicOutlined />,
  UnderlineOutlined: <UnderlineOutlined />,
  StrikethroughOutlined: <StrikethroughOutlined />,
  RedoOutlined: <RedoOutlined />,
  UndoOutlined: <UndoOutlined />,
  ZoomInOutlined: <ZoomInOutlined />,
  ZoomOutOutlined: <ZoomOutOutlined />,
  FontColorsOutlined: <FontColorsOutlined />,
  FontSizeOutlined: <FontSizeOutlined />,
  LineHeightOutlined: <LineHeightOutlined />,
  DashOutlined: <DashOutlined />,
  SmallDashOutlined: <SmallDashOutlined />,
  SortAscendingOutlined: <SortAscendingOutlined />,
  SortDescendingOutlined: <SortDescendingOutlined />,
  DragOutlined: <DragOutlined />,
  OrderedListOutlined: <OrderedListOutlined />,
  UnorderedListOutlined: <UnorderedListOutlined />,
  RadiusSettingOutlined: <RadiusSettingOutlined />,
  ColumnWidthOutlined: <ColumnWidthOutlined />,
  ColumnHeightOutlined: <ColumnHeightOutlined />,
  // 数据类图标
  AreaChartOutlined: <AreaChartOutlined />,
  PieChartOutlined: <PieChartOutlined />,
  BarChartOutlined: <BarChartOutlined />,
  DotChartOutlined: <DotChartOutlined />,
  LineChartOutlined: <LineChartOutlined />,
  RadarChartOutlined: <RadarChartOutlined />,
  HeatMapOutlined: <HeatMapOutlined />,
  FallOutlined: <FallOutlined />,
  RiseOutlined: <RiseOutlined />,
  StockOutlined: <StockOutlined />,
  BoxPlotOutlined: <BoxPlotOutlined />,
  FundOutlined: <FundOutlined />,
  SlidersOutlined: <SlidersOutlined />,
  // 品牌和标识
  AndroidOutlined: <AndroidOutlined />,
  AppleOutlined: <AppleOutlined />,
  WindowsOutlined: <WindowsOutlined />,
  IeOutlined: <IeOutlined />,
  ChromeOutlined: <ChromeOutlined />,
  GithubOutlined: <GithubOutlined />,
  AliwangwangOutlined: <AliwangwangOutlined />,
  DingdingOutlined: <DingdingOutlined />,
  WeiboSquareOutlined: <WeiboSquareOutlined />,
  WeiboCircleOutlined: <WeiboCircleOutlined />,
  TaobaoCircleOutlined: <TaobaoCircleOutlined />,
  Html5Outlined: <Html5Outlined />,
  WeiboOutlined: <WeiboOutlined />,
  TwitterOutlined: <TwitterOutlined />,
  WechatOutlined: <WechatOutlined />,
  YoutubeOutlined: <YoutubeOutlined />,
  AlipayCircleOutlined: <AlipayCircleOutlined />,
  TaobaoOutlined: <TaobaoOutlined />,
  SkypeOutlined: <SkypeOutlined />,
  QqOutlined: <QqOutlined />,
  MediumWorkmarkOutlined: <MediumWorkmarkOutlined />,
  GitlabOutlined: <GitlabOutlined />,
  MediumOutlined: <MediumOutlined />,
  LinkedinOutlined: <LinkedinOutlined />,
  GooglePlusOutlined: <GooglePlusOutlined />,
  DropboxOutlined: <DropboxOutlined />,
  FacebookOutlined: <FacebookOutlined />,
  CodepenOutlined: <CodepenOutlined />,
  CodeSandboxOutlined: <CodeSandboxOutlined />,
  AmazonOutlined: <AmazonOutlined />,
  GoogleOutlined: <GoogleOutlined />,
  CodepenCircleOutlined: <CodepenCircleOutlined />,
  AlipayOutlined: <AlipayOutlined />,
  AntDesignOutlined: <AntDesignOutlined />,
  AntCloudOutlined: <AntCloudOutlined />,
  AliyunOutlined: <AliyunOutlined />,
  ZhihuOutlined: <ZhihuOutlined />,
  SlackOutlined: <SlackOutlined />,
  SlackSquareOutlined: <SlackSquareOutlined />,
  BehanceOutlined: <BehanceOutlined />,
  BehanceSquareOutlined: <BehanceSquareOutlined />,
  DribbbleOutlined: <DribbbleOutlined />,
  DribbbleSquareOutlined: <DribbbleSquareOutlined />,
  InstagramOutlined: <InstagramOutlined />,
  YuqueOutlined: <YuqueOutlined />,
  AlibabaOutlined: <AlibabaOutlined />,
  YahooOutlined: <YahooOutlined />,
  RedditOutlined: <RedditOutlined />,
  SketchOutlined: <SketchOutlined />,
  //网站通用图标
  AccountBookOutlined: <AccountBookOutlined />,
  AimOutlined: <AimOutlined />,
  AlertOutlined: <AlertOutlined />,
  ApartmentOutlined: <ApartmentOutlined />,
  ApiOutlined: <ApiOutlined />,
  AppstoreAddOutlined: <AppstoreAddOutlined />,
  AppstoreOutlined: <AppstoreOutlined />,
  AudioOutlined: <AudioOutlined />,
  AudioMutedOutlined: <AudioMutedOutlined />,
  AuditOutlined: <AuditOutlined />,
  BankOutlined: <BankOutlined />,
  BarcodeOutlined: <BarcodeOutlined />,
  BarsOutlined: <BarsOutlined />,
  BellOutlined: <BellOutlined />,
  BlockOutlined: <BlockOutlined />,
  BookOutlined: <BookOutlined />,
  BorderOutlined: <BorderOutlined />,
  BorderlessTableOutlined: <BorderlessTableOutlined />,
  BranchesOutlined: <BranchesOutlined />,
  BugOutlined: <BugOutlined />,
  BuildOutlined: <BuildOutlined />,
  BulbOutlined: <BulbOutlined />,
  CalculatorOutlined: <CalculatorOutlined />,
  CalendarOutlined: <CalendarOutlined />,
  CameraOutlined: <CameraOutlined />,
  CarOutlined: <CarOutlined />,
  CarryOutOutlined: <CarryOutOutlined />,
  CiCircleOutlined: <CiCircleOutlined />,
  CiOutlined: <CiOutlined />,
  ClearOutlined: <ClearOutlined />,
  CloudDownloadOutlined: <CloudDownloadOutlined />,
  CloudOutlined: <CloudOutlined />,
  CloudServerOutlined: <CloudServerOutlined />,
  CloudSyncOutlined: <CloudSyncOutlined />,
  CloudUploadOutlined: <CloudUploadOutlined />,
  ClusterOutlined: <ClusterOutlined />,
  CodeOutlined: <CodeOutlined />,
  CoffeeOutlined: <CoffeeOutlined />,
  CommentOutlined: <CommentOutlined />,
  CompassOutlined: <CompassOutlined />,
  CompressOutlined: <CompressOutlined />,
  ConsoleSqlOutlined: <ConsoleSqlOutlined />,
  ContactsOutlined: <ContactsOutlined />,
  ContainerOutlined: <ContainerOutlined />,
  ControlOutlined: <ControlOutlined />,
  CopyrightOutlined: <CopyrightOutlined />,
  CreditCardOutlined: <CreditCardOutlined />,
  CrownOutlined: <CrownOutlined />,
  CustomerServiceOutlined: <CustomerServiceOutlined />,
  DashboardOutlined: <DashboardOutlined />,
  DatabaseOutlined: <DatabaseOutlined />,
  DeleteColumnOutlined: <DeleteColumnOutlined />,
  DeleteRowOutlined: <DeleteRowOutlined />,
  DeliveredProcedureOutlined: <DeliveredProcedureOutlined />,
  DeploymentUnitOutlined: <DeploymentUnitOutlined />,
  DesktopOutlined: <DesktopOutlined />,
  DingtalkOutlined: <DingtalkOutlined />,
  DisconnectOutlined: <DisconnectOutlined />,
  DislikeOutlined: <DislikeOutlined />,
  DollarCircleOutlined: <DollarCircleOutlined />,
  DollarOutlined: <DollarOutlined />,
  DownloadOutlined: <DownloadOutlined />,
  EllipsisOutlined: <EllipsisOutlined />,
  EnvironmentOutlined: <EnvironmentOutlined />,
  EuroCircleOutlined: <EuroCircleOutlined />,
  EuroOutlined: <EuroOutlined />,
  ExceptionOutlined: <ExceptionOutlined />,
  ExpandAltOutlined: <ExpandAltOutlined />,
  ExpandOutlined: <ExpandOutlined />,
  ExperimentOutlined: <ExperimentOutlined />,
  ExportOutlined: <ExportOutlined />,
  EyeOutlined: <EyeOutlined />,
  EyeInvisibleOutlined: <EyeInvisibleOutlined />,
  FieldBinaryOutlined: <FieldBinaryOutlined />,
  FieldNumberOutlined: <FieldNumberOutlined />,
  FieldStringOutlined: <FieldStringOutlined />,
  FieldTimeOutlined: <FieldTimeOutlined />,
  FileAddOutlined: <FileAddOutlined />,
  FileDoneOutlined: <FileDoneOutlined />,
  FileExcelOutlined: <FileExcelOutlined />,
  FileExclamationOutlined: <FileExclamationOutlined />,
  FileOutlined: <FileOutlined />,
  FileGifOutlined: <FileGifOutlined />,
  FileImageOutlined: <FileImageOutlined />,
  FileJpgOutlined: <FileJpgOutlined />,
  FileMarkdownOutlined: <FileMarkdownOutlined />,
  FilePdfOutlined: <FilePdfOutlined />,
  FilePptOutlined: <FilePptOutlined />,
  FileProtectOutlined: <FileProtectOutlined />,
  FileSearchOutlined: <FileSearchOutlined />,
  FileSyncOutlined: <FileSyncOutlined />,
  FileTextOutlined: <FileTextOutlined />,
  FileUnknownOutlined: <FileUnknownOutlined />,
  FileWordOutlined: <FileWordOutlined />,
  FileZipOutlined: <FileZipOutlined />,
  FilterOutlined: <FilterOutlined />,
  FireOutlined: <FireOutlined />,
  FlagOutlined: <FlagOutlined />,
  FolderAddOutlined: <FolderAddOutlined />,
  FolderOutlined: <FolderOutlined />,
  FolderOpenOutlined: <FolderOpenOutlined />,
  FolderViewOutlined: <FolderViewOutlined />,
  ForkOutlined: <ForkOutlined />,
  FormatPainterOutlined: <FormatPainterOutlined />,
  FrownOutlined: <FrownOutlined />,
  FunctionOutlined: <FunctionOutlined />,
  FundProjectionScreenOutlined: <FundProjectionScreenOutlined />,
  FundViewOutlined: <FundViewOutlined />,
  FunnelPlotOutlined: <FunnelPlotOutlined />,
  GatewayOutlined: <GatewayOutlined />,
  GifOutlined: <GifOutlined />,
  GiftOutlined: <GiftOutlined />,
  GlobalOutlined: <GlobalOutlined />,
  GoldOutlined: <GoldOutlined />,
  GroupOutlined: <GroupOutlined />,
  HddOutlined: <HddOutlined />,
  HeartOutlined: <HeartOutlined />,
  HistoryOutlined: <HistoryOutlined />,
  HomeOutlined: <HomeOutlined />,
  HourglassOutlined: <HourglassOutlined />,
  IdcardOutlined: <IdcardOutlined />,
  ImportOutlined: <ImportOutlined />,
  InboxOutlined: <InboxOutlined />,
  InsertRowAboveOutlined: <InsertRowAboveOutlined />,
  InsertRowBelowOutlined: <InsertRowBelowOutlined />,
  InsertRowLeftOutlined: <InsertRowLeftOutlined />,
  InsertRowRightOutlined: <InsertRowRightOutlined />,
  InsuranceOutlined: <InsuranceOutlined />,
  InteractionOutlined: <InteractionOutlined />,
  KeyOutlined: <KeyOutlined />,
  LaptopOutlined: <LaptopOutlined />,
  LayoutOutlined: <LayoutOutlined />,
  LikeOutlined: <LikeOutlined />,
  LineOutlined: <LineOutlined />,
  LinkOutlined: <LinkOutlined />,
  Loading3QuartersOutlined: <Loading3QuartersOutlined />,
  LoadingOutlined: <LoadingOutlined />,
  LockOutlined: <LockOutlined />,
  MacCommandOutlined: <MacCommandOutlined />,
  MailOutlined: <MailOutlined />,
  ManOutlined: <ManOutlined />,
  MedicineBoxOutlined: <MedicineBoxOutlined />,
  MehOutlined: <MehOutlined />,
  MenuOutlined: <MenuOutlined />,
  MergeCellsOutlined: <MergeCellsOutlined />,
  MessageOutlined: <MessageOutlined />,
  MobileOutlined: <MobileOutlined />,
  MoneyCollectOutlined: <MoneyCollectOutlined />,
  MonitorOutlined: <MonitorOutlined />,
  MoreOutlined: <MoreOutlined />,
  NodeCollapseOutlined: <NodeCollapseOutlined />,
  NodeExpandOutlined: <NodeExpandOutlined />,
  NodeIndexOutlined: <NodeIndexOutlined />,
  NotificationOutlined: <NotificationOutlined />,
  NumberOutlined: <NumberOutlined />,
  OneToOneOutlined: <OneToOneOutlined />,
  PaperClipOutlined: <PaperClipOutlined />,
  PartitionOutlined: <PartitionOutlined />,
  PayCircleOutlined: <PayCircleOutlined />,
  PercentageOutlined: <PercentageOutlined />,
  PhoneOutlined: <PhoneOutlined />,
  PictureOutlined: <PictureOutlined />,
  PlaySquareOutlined: <PlaySquareOutlined />,
  PoundCircleOutlined: <PoundCircleOutlined />,
  PoundOutlined: <PoundOutlined />,
  PoweroffOutlined: <PoweroffOutlined />,
  PrinterOutlined: <PrinterOutlined />,
  ProfileOutlined: <ProfileOutlined />,
  ProjectOutlined: <ProjectOutlined />,
  PropertySafetyOutlined: <PropertySafetyOutlined />,
  PullRequestOutlined: <PullRequestOutlined />,
  PushpinOutlined: <PushpinOutlined />,
  QrcodeOutlined: <QrcodeOutlined />,
  ReadOutlined: <ReadOutlined />,
  ReconciliationOutlined: <ReconciliationOutlined />,
  RedEnvelopeOutlined: <RedEnvelopeOutlined />,
  ReloadOutlined: <ReloadOutlined />,
  RestOutlined: <RestOutlined />,
  RobotOutlined: <RobotOutlined />,
  RocketOutlined: <RocketOutlined />,
  RotateLeftOutlined: <RotateLeftOutlined />,
  RotateRightOutlined: <RotateRightOutlined />,
  SafetyCertificateOutlined: <SafetyCertificateOutlined />,
  SafetyOutlined: <SafetyOutlined />,
  SaveOutlined: <SaveOutlined />,
  ScanOutlined: <ScanOutlined />,
  ScheduleOutlined: <ScheduleOutlined />,
  SearchOutlined: <SearchOutlined />,
  SecurityScanOutlined: <SecurityScanOutlined />,
  SelectOutlined: <SelectOutlined />,
  SendOutlined: <SendOutlined />,
  SettingOutlined: <SettingOutlined />,
  ShakeOutlined: <ShakeOutlined />,
  ShareAltOutlined: <ShareAltOutlined />,
  ShopOutlined: <ShopOutlined />,
  ShoppingCartOutlined: <ShoppingCartOutlined />,
  ShoppingOutlined: <ShoppingOutlined />,
  SisternodeOutlined: <SisternodeOutlined />,
  SkinOutlined: <SkinOutlined />,
  SmileOutlined: <SmileOutlined />,
  SolutionOutlined: <SolutionOutlined />,
  SoundOutlined: <SoundOutlined />,
  SplitCellsOutlined: <SplitCellsOutlined />,
  StarOutlined: <StarOutlined />,
  SubnodeOutlined: <SubnodeOutlined />,
  SwitcherOutlined: <SwitcherOutlined />,
  SyncOutlined: <SyncOutlined />,
  TableOutlined: <TableOutlined />,
  TabletOutlined: <TabletOutlined />,
  TagOutlined: <TagOutlined />,
  TagsOutlined: <TagsOutlined />,
  TeamOutlined: <TeamOutlined />,
  ThunderboltOutlined: <ThunderboltOutlined />,
  ToTopOutlined: <ToTopOutlined />,
  ToolOutlined: <ToolOutlined />,
  TrademarkCircleOutlined: <TrademarkCircleOutlined />,
  TrademarkOutlined: <TrademarkOutlined />,
  TransactionOutlined: <TransactionOutlined />,
  TranslationOutlined: <TranslationOutlined />,
  TrophyOutlined: <TrophyOutlined />,
  UngroupOutlined: <UngroupOutlined />,
  UnlockOutlined: <UnlockOutlined />,
  UploadOutlined: <UploadOutlined />,
  UsbOutlined: <UsbOutlined />,
  UserAddOutlined: <UserAddOutlined />,
  UserDeleteOutlined: <UserDeleteOutlined />,
  UserOutlined: <UserOutlined />,
  UserSwitchOutlined: <UserSwitchOutlined />,
  UsergroupAddOutlined: <UsergroupAddOutlined />,
  UsergroupDeleteOutlined: <UsergroupDeleteOutlined />,
  VerifiedOutlined: <VerifiedOutlined />,
  VideoCameraAddOutlined: <VideoCameraAddOutlined />,
  VideoCameraOutlined: <VideoCameraOutlined />,
  WalletOutlined: <WalletOutlined />,
  WhatsAppOutlined: <WhatsAppOutlined />,
  WifiOutlined: <WifiOutlined />,
  WomanOutlined: <WomanOutlined />,
};

export default iconEnum;
